services:
  postgres:
    image: postgres:16-alpine
    container_name: oficina48-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: oficina48_billing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  localstack:
    image: localstack/localstack:3.4.0
    container_name: oficina48-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./localstack-init:/etc/localstack/init/ready.d
      - localstack_data:/var/lib/localstack
    healthcheck:
      test: ["CMD-SHELL", "awslocal sqs list-queues"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  localstack_data:
