sonar.projectKey=oficina48_Billing_Service
sonar.projectName=Oficina48_Billing_Service
sonar.sourceEncoding=UTF-8

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml