apiVersion: v1
kind: Secret

metadata:
  name: billing-service-secret

type: Opaque

stringData:
  SPRING_DATASOURCE_PASSWORD: ""
  NEW_RELIC_LICENSE_KEY: ""
  MRCPAGO_ACCESS_TOKEN: ""
  MRCPAGO_PUBLIC_KEY: ""
  MRCPAGO_PRIVATE_KEY: ""
  MRCPAGO_CLIENT_SECRETS: ""
  MRCPAGO_WEBHOOK_URL: ""